apiVersion: apps/v1
kind: Deployment
metadata:
  name: weborder-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: weborder
  template:
    metadata:
      labels:
        app: weborder
    spec:
      containers:
        - name: weborder
          image: web-order-service:v1
          ports:
            - containerPort: 5001
---
apiVersion: v1
kind: Service
metadata:
  name: web-order-service
spec:
  selector:
    app: weborder
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
