apiVersion: apps/v1
kind: Deployment
metadata:
  name: weborder-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: weborder
  template:
    metadata:
      labels:
        app: weborder
    spec:
      containers:
      - name: weborder
        image: web-order-service
        ports:
        - containerPort: 5003
---
apiVersion: v1
kind: Service
metadata:
  name: web-order-service
spec:
  selector:
    app: weborder
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5003
