apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderconfirmation-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: orderconfirmation
  template:
    metadata:
      labels:
        app: orderconfirmation
    spec:
      containers:
        - name: orderconfirmation
          image: order-confirmation-service:v1
          ports:
            - containerPort: 5003
---
apiVersion: v1
kind: Service
metadata:
  name: orderconfirmation-service
spec:
  selector:
    app: orderconfirmation
  ports:
    - protocol: TCP
      port: 5003
      targetPort: 5003
