apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderconfirmation-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: orderconfirmation
  template:
    metadata:
      labels:
        app: orderconfirmation
    spec:
      containers:
      - name: orderconfirmation
        image: orderconfirmation-service
        ports:
        - containerPort: 5001
---
apiVersion: v1
kind: Service
metadata:
  name: orderconfirmation-service
spec:
  selector:
    app: orderconfirmation
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5001
