apiVersion: apps/v1
kind: Deployment
metadata:
  name: wishlist-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wishlist
  template:
    metadata:
      labels:
        app: wishlist
    spec:
      containers:
        - name: wishlist
          image: wishlist-service:v1
          ports:
            - containerPort: 5005
---
apiVersion: v1
kind: Service
metadata:
  name: wishlist-service
spec:
  selector:
    app: wishlist
  ports:
    - protocol: TCP
      port: 5005
      targetPort: 5005
