apiVersion: apps/v1
kind: Deployment
metadata:
  name: ordertracking-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ordertracking
  template:
    metadata:
      labels:
        app: ordertracking
    spec:
      containers:
      - name: ordertracking
        image: ordertracking-service
        ports:
        - containerPort: 5002
---
apiVersion: v1
kind: Service
metadata:
  name: ordertracking-service
spec:
  selector:
    app: ordertracking
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5002
